name: Publish GH Page
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.5
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Install Racket Dependencies
        run: |
          raco pkg install --batch --auto racket/gui
      - name: Build Scribble Docs
        run: |
          racket  -l racket/gui -l-  scribble/run    ++xref-in setup/xref load-collections-xref   --htmls --redirect-main http://docs.racket-lang.org/ script.scrbl
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
